#!/usr/bin/env python
import sys, csv
from isbntools.app import *
import unicodedata 

entries=list()

with open(sys.argv[1],'r') as f:
    for line in f:
        book = line.strip()
        query = book.replace(' ', '+')
        isbn = isbn_from_words(query)
        if isbn:
            m = meta(isbn)
            if not m:
                m = {'ISBN-13':isbn}
            m['search']=book
            if 'Authors' in m:
                m['Authors']=m['Authors'][0]
            print "%s %s" % (isbn,book) 
            print m
            print ""
            entries.append(m)

headers=dict()
for entry in entries:
    for h in entry.keys():
        headers[h]=True

with open('books.csv','w') as csvfile:
    w = csv.DictWriter(csvfile,fieldnames=headers.keys())
    w.writeheader()
    for entry in entries:
        for k in entry.keys():
            #entry[k] = unicodedata.normalize('NFKD',entry[k].decode('utf-8')).encode('ascii','ignore')
            entry[k] = entry[k].encode('UTF-8')
        w.writerow(entry)
